[package]
name = "command-auspex"
version = "0.1.4"
description = "Command Auspex — list-building battle simulator"
authors = ["Tom Hunter"]
edition = "2021"
rust-version = "1.77"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
tauri-plugin-sql = { version = "2", features = ["sqlite"] }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
